In [2]:
import numpy as np

In [1]:
import matplotlib.pyplot as plt

In [19]:
import torch

In [139]:
true = torch.randint(high=6, size = (3,7,7))

In [140]:
true.shape

torch.Size([3, 7, 7])

In [141]:
true.unique()

tensor([0, 1, 2, 3, 4, 5])

In [49]:
pred = torch.rand(3,6,7,7)

In [31]:
pred.shape

torch.Size([3, 6, 7, 7])

In [32]:
pred.unique

<bound method Tensor.unique of tensor([[[[0.4476, 0.4240, 0.8377, 0.1381, 0.9615, 0.0647, 0.6155],
          [0.6122, 0.0714, 0.9042, 0.2272, 0.7150, 0.0378, 0.6216],
          [0.6129, 0.9453, 0.8800, 0.4837, 0.7086, 0.6027, 0.4328],
          [0.0282, 0.5206, 0.8171, 0.4700, 0.2072, 0.7190, 0.9096],
          [0.5962, 0.6105, 0.2776, 0.2839, 0.0541, 0.0870, 0.9347],
          [0.2462, 0.4332, 0.7995, 0.5829, 0.2101, 0.9247, 0.9601],
          [0.5411, 0.9660, 0.2447, 0.9019, 0.0087, 0.3098, 0.3611]],

         [[0.5592, 0.9145, 0.4325, 0.6156, 0.0292, 0.6773, 0.1399],
          [0.1634, 0.4076, 0.5509, 0.2562, 0.3422, 0.9194, 0.4851],
          [0.4562, 0.8101, 0.7730, 0.5347, 0.9032, 0.2083, 0.7603],
          [0.1881, 0.8534, 0.8919, 0.7624, 0.6575, 0.7114, 0.6129],
          [0.7243, 0.1069, 0.3920, 0.5405, 0.3543, 0.9671, 0.4103],
          [0.7578, 0.3719, 0.7793, 0.2759, 0.9598, 0.7580, 0.0022],
          [0.1417, 0.3884, 0.2951, 0.2284, 0.2120, 0.0555, 0.5107]],

         [[0.

In [33]:
from torch.nn import functional as F

In [34]:
pred.shape

torch.Size([3, 6, 7, 7])

In [35]:
pred = F.softmax(pred,dim = 1)

In [36]:
pred.unique

<bound method Tensor.unique of tensor([[[[0.1662, 0.1479, 0.2325, 0.1522, 0.2900, 0.0960, 0.1831],
          [0.1839, 0.1365, 0.2244, 0.1341, 0.2429, 0.1012, 0.1566],
          [0.2069, 0.2091, 0.2289, 0.1320, 0.1705, 0.1734, 0.1405],
          [0.0978, 0.1781, 0.2048, 0.1530, 0.1155, 0.2174, 0.2545],
          [0.1702, 0.1685, 0.1493, 0.1349, 0.1401, 0.1021, 0.2553],
          [0.1392, 0.1440, 0.2030, 0.1673, 0.1154, 0.2096, 0.2103],
          [0.1955, 0.2394, 0.1366, 0.1815, 0.1034, 0.1508, 0.1461]],

         [[0.1859, 0.2416, 0.1550, 0.2454, 0.1142, 0.1772, 0.1138],
          [0.1174, 0.1910, 0.1576, 0.1380, 0.1673, 0.2443, 0.1366],
          [0.1769, 0.1826, 0.2057, 0.1389, 0.2071, 0.1169, 0.1949],
          [0.1148, 0.2484, 0.2208, 0.2050, 0.1811, 0.2158, 0.1891],
          [0.1934, 0.1019, 0.1674, 0.1744, 0.1891, 0.2462, 0.1511],
          [0.2321, 0.1355, 0.1990, 0.1231, 0.2442, 0.1774, 0.0807],
          [0.1311, 0.1344, 0.1436, 0.0926, 0.1267, 0.1169, 0.1697]],

         [[0.

In [37]:
pred.shape

torch.Size([3, 6, 7, 7])

In [38]:
true.shape

torch.Size([3, 7, 7])

In [42]:
true = true.view(3,-1)

In [43]:
true.shape

torch.Size([3, 49])

In [44]:
pred = pred.view(3,-1)

In [45]:
pred.shape

torch.Size([3, 294])

In [50]:
true.shape

torch.Size([3, 7, 7])

In [52]:
true.unique()

tensor([0, 1, 2, 3, 4, 5])

In [92]:
t_1_h = torch.zeros(true.shape[0],6,true.shape[1],true.shape[2])

In [59]:
t_1_h.shape

torch.Size([3, 6, 7, 7])

In [60]:
for j in range(3):
    for i in range(6):
        t_1_h[j][i][true[j]==i] = 1 

In [61]:
t_1_h.unique()

tensor([0., 1.])

In [64]:
t_1_h.shape

torch.Size([3, 6, 7, 7])

In [65]:
true.shape

torch.Size([3, 7, 7])

In [74]:
for i in range(6):
    t_1_h[:,i,:,:][true[0]==i] = 1

IndexError: The shape of the mask [7, 7] at index 0 does not match the shape of the indexed tensor [3, 7, 7] at index 0

In [68]:
t_1_h

tensor([[[[0., 0., 0., 0., 0., 1., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0., 0., 1.],
          [0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.]],

         [[0., 0., 1., 0., 0., 0., 1.],
          [0., 0., 1., 0., 0., 1., 0.],
          [0., 1., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 1., 0., 0., 0., 0., 0.],
          [0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.]],

         [[1., 0., 0., 0., 1., 0., 0.],
          [0., 1., 0., 0., 0., 0., 1.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.],
          [1., 0., 0., 0., 0., 1., 0.]],

         [[0., 1., 0., 0., 0., 0., 0.],
          [1., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 1.,

In [72]:
true[0].shape

torch.Size([7, 7])

In [80]:
true[0]

tensor([[2, 3, 1, 5, 2, 0, 1],
        [3, 2, 1, 5, 3, 1, 2],
        [0, 1, 5, 4, 0, 4, 4],
        [4, 4, 0, 5, 1, 3, 0],
        [4, 1, 0, 4, 2, 4, 3],
        [3, 4, 3, 1, 0, 2, 3],
        [2, 4, 3, 0, 5, 2, 5]])

In [81]:
t = true[1] == 2

In [82]:
t

tensor([[0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0]], dtype=torch.uint8)

In [78]:
t.shape

torch.Size([7, 7])

In [84]:
t_1_h[:,0,:,:].shape

torch.Size([3, 7, 7])

In [91]:
true.unique()

tensor([0, 1, 2, 3, 4, 5])

In [108]:
true_e = torch.eye(6)

In [95]:
true[0]

tensor([[2, 5, 2, 1, 2, 0, 5],
        [3, 3, 3, 4, 2, 5, 4],
        [4, 1, 2, 0, 3, 3, 2],
        [0, 2, 5, 3, 3, 0, 4],
        [2, 5, 3, 1, 0, 4, 4],
        [5, 4, 1, 4, 0, 0, 5],
        [5, 5, 5, 1, 0, 5, 0]])

In [96]:
true[0] == 2

tensor([[1, 0, 1, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]], dtype=torch.uint8)

In [107]:
t_1h = torch.zeros(6,7,7)

In [99]:
t_1.shape

torch.Size([6, 7, 7])

In [114]:
true_e[0]

tensor([1., 0., 0., 0., 0., 0.])

In [116]:
truec = true[0].clone()

In [117]:
truec.shape

torch.Size([7, 7])

In [118]:
truec

tensor([[2, 5, 2, 1, 2, 0, 5],
        [3, 3, 3, 4, 2, 5, 4],
        [4, 1, 2, 0, 3, 3, 2],
        [0, 2, 5, 3, 3, 0, 4],
        [2, 5, 3, 1, 0, 4, 4],
        [5, 4, 1, 4, 0, 0, 5],
        [5, 5, 5, 1, 0, 5, 0]])

In [119]:
t_1h.shape

torch.Size([6, 7, 7])

In [124]:
truec==1

tensor([[0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0]], dtype=torch.uint8)

In [127]:
(truec==1).nonzero()[0]

tensor([0, 3])

In [125]:
true_e 

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [153]:
c = F.one_hot(true,num_classes=6)

In [161]:
truec.shape

torch.Size([7, 7])

In [154]:
true[1][4][5]

tensor(0)

In [155]:
c[1][4][5]

tensor([1, 0, 0, 0, 0, 0])

In [160]:
c.dtype

torch.int64

In [156]:
cp = c.permute(0,3,1,2)

In [157]:
cp.shape

torch.Size([3, 6, 7, 7])

In [158]:
cpt= cp[:,1,:,:]

In [159]:
cpt.shape

torch.Size([3, 7, 7])

In [152]:
cp[1,:,4,5]

tensor([1, 0, 0, 0, 0, 0])

In [148]:
c.shape

torch.Size([3, 7, 7, 6])

In [126]:
t_1h.shape

torch.Size([6, 7, 7])

In [ ]:
t_1h 

In [120]:
t_1h[:,4,5] 

tensor([0., 0., 0., 0., 0., 0.])

In [ ]:
for i in range(6):
    tru

In [110]:
t_1h[true[0] == 1] = true_e[1]

IndexError: The shape of the mask [7, 7] at index 0 does not match the shape of the indexed tensor [6, 7, 7] at index 0

In [103]:
true[0].shape

torch.Size([7, 7])

In [104]:
true[0] == 1

tensor([[0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0]], dtype=torch.uint8)

TypeError: where() missing 1 required positional arguments: "other"

In [1]:
from PIL import Image

In [2]:
import matplotlib.pyplot as plt

In [18]:
im = plt.imread('/home/siddharth/Downloads/Caltech_0051456_abide_cc.nii-slice000.jpg')

In [19]:
im.shape

(512, 512, 3)

In [14]:
img = Image.fromarray(im)

In [15]:
img = img.convert('L')

In [9]:
import numpy as np

In [16]:
img = np.array(img)

In [17]:
img.shape

(512, 512)